apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
  name: {{ include "backend-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
        env:
        - name: SPRING_PROFILE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: ENVIRONMENT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: SPRINGDATASOURCEUSERNAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: SPRINGDATASOURCEPASSWORD
