apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
  name: {{ include "backend-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: ENVIRONMENT
        - name: DB_SERVER_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: DBSERVERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: DBNAME
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: SPRINGDATASOURCEURL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: SPRINGDATASOURCEUSERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: SPRINGDATASOURCEPASSWORD
