apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
  name: {{ include "backend-chart.fullname" . }}
spec:
  ports:
  - name: backend-port
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "backend-chart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
