trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform_Validate
  jobs:
  - job: Validate
    displayName: Validation
    steps:
    - task: TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: '1.0.7'

    - task: TerraformTaskV2@2
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        backendAzureRmResourceGroupName: 'test-aks'
        backendAzureRmStorageAccountName: 'tfaks9'
        backendAzureRmContainerName: 'akstfstate'
        backendAzureRmKey: 'izc726yGbvWcMq2QfSt/Pu26VeHhBR1nQM64c6wEoFEHqhnxB3dak4XcAiQFh5dVzFz4YClI19WP05/ZNcfj+w=='

    - task: TerraformTaskV2@2
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'