
trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Java_Maven_Building
  displayName: Java Maven Building
  jobs:
  - job: Java_Maven_Build
    displayName: Java Maven Build
    pool:
      vmImage: ubuntu-latest 
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/springboot-backend/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/springboot-backend/target/'
        Contents: |
          *.jar
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'target'
        publishLocation: 'Container'

- stage: Maven_Building
  displayName: Maven Building
  jobs:
  - job: Maven_Build
    displayName: Maven Build
    pool:
      vmImage: ubuntu-latest 
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |          
          ls -lrt '$(build.artifactstagingdirectory)'

    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        downloadPath: '$(System.ArtifactsDirectory)'
