
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: '$(Build.SourcesDirectory)/springboot-backend/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/springboot-backend/target/*.jar'
    ArtifactName: 'target'
    publishLocation: 'Container'

- task: Bash@3
  displayName: Jar finding
  inputs:
    targetType: 'inline'
    script: |
      ls -lrt '$(Build.SourcesDirectory)/springboot-backend/target/' 
      ls -lrt '$(Build.ArtifactStagingDirectory)/'