# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      continueOnError: true
      displayName: "Linting Dockerfile"
      inputs:
        targetType: 'inline'
        script: |
          docker run --rm -i hadolint/hadolint < '$(Build.SourcesDirectory)/springboot-backend/Dockerfile'
          
          # check if the Hadolint command found issues or not
          if [ $? != 0 ];
          then
            echo "##vso[task.logissue type=error]Lint scanning found errors in the Dockerfile that need to be resolved!"
            echo "##vso[task.complete result=Failed]Docker Lint reporting errors"
          else
            echo "##vso[task.complete result=Succeeded]Docker Lint succeeded"
          fi
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: sb
        dockerfile: '$(Build.SourcesDirectory)/springboot-backend/Dockerfile'
        tags: "1.60"

    - task: Bash@3
      displayName: Download & Install Trivy For Image Scan
      inputs:
        targetType: 'inline'
        script: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.19.2_Linux-64bit.deb

    - task: Bash@3
      displayName: Trivy Scan
      inputs:
        targetType: 'inline'
        script: |
          trivy image sb:1.60