repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: gatekeeper
  url: https://open-policy-agent.github.io/gatekeeper/charts
# - name: aad-pod-identity
#   url: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

environments:
  default:
    values:
      - "values.yaml"
  dev:
    values:
      - "values.yaml"

releases:
- name: ingress-nginx
  namespace: default
  chart: ingress-nginx/ingress-nginx
  labels:
    name: nginx-ingress
  version: 4.1.1
  values:
    - controller:
        replicaCount: 2
        nodeSelector:
          beta.kubernetes.io/os: linux
    - defaultBackend:
        nodeSelector:
          beta.kubernetes.io/os: linux

- name: gatekeeper
  namespace: default
  chart: gatekeeper/gatekeeper
  labels:
    name: gatekeeper
  version: 3.8.1
  values:
    - controllerManager:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            {{ toYaml .Values.controllerManager.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution | nindent 14 }}

# - name: aad-pod-identity
#   namespace: default
#   chart: aad-pod-identity/aad-pod-identity
#   labels:
#     name: aad-pod-identity
#   version: 4.1.9
#   values:
#     - nmi:
#         tolerations: 
#         {{ toYaml .Values.defaultToleration | nindent 10 }}