repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

environments:
  default:
    values:
      - "values.yaml"
  dev:
    values:
      - "values.yaml"

releases:
- name: ingress-nginx
  namespace: default
  chart: ingress-nginx/ingress-nginx
  labels:
    name: nginx-ingress
  version: 4.1.1
  values:
    - controller:
        replicaCount: 2
        nodeSelector:
          beta.kubernetes.io/os: linux
    - defaultBackend:
        nodeSelector:
          beta.kubernetes.io/os: linux