repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: aad-pod-identity
  url: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
- name: itscontained
  url: https://charts.itscontained.io

environments:
  default:
    values:
      - "values.yaml"
  dev:
    values:
      - "values.yaml"

releases:
- name: ingress-nginx
  namespace: default
  chart: ingress-nginx/ingress-nginx
  labels:
    name: nginx-ingress
  version: 4.1.1
  values:
    - controller:
        replicaCount: 2
        nodeSelector:
          beta.kubernetes.io/os: linux
    - defaultBackend:
        nodeSelector:
          beta.kubernetes.io/os: linux

# Enables pod-identity on cluster with CRDs
- name: aad-pod-identity
  namespace: default
  chart: aad-pod-identity/aad-pod-identity
  labels:
   name: aad-pod-identity
  version: 4.1.10

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  labels:
    name: cert-manager
  version: 1.8.0
  values:
    - installCRDs: true

- name: cert-manager-issuer
  chart: itscontained/raw
  namespace: default
  version:  0.2.5
  labels:
   name: itscontained
  disableValidation: true
  values:
    - resources:
        - apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: bahri.nipun@gmail.com
              privateKeySecretRef:
                name: letsencrypt
              solvers:
              - http01:
                  ingress:
                    class: nginx

