apiVersion: v1
data:
  EMPLOYEE_API_BASE_URL_VALUE: https://20.76.235.52:8443/api/v1/skills
  SKILL_API_BASE_URL_VALUE: https://20.76.235.52:8443/api/v1/skills
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
