trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: global-variables
- name: terraformVersion
  value: 1.0.7
- name: tfstatePath
  value: terraform.tfstate
- name: location
  value: westeurope

stages:
- stage: Terraform_Validate
  jobs:
  - job: Validate
    displayName: Validation
    steps:
    - task: AzureCLI@2
      displayName: 'Get Latest Kubernetes Version'
      inputs:
        azureSubscription: 'aks_spn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          version=$(az aks get-versions --location $(location) --query orchestrators[-1].orchestratorVersion --output tsv)
          echo "##vso[task.setvariable variable=kubernetesVersion;]$version"
          echo "kubernetesVersion: $(kubernetesVersion)"
        addSpnToEnvironment: true
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: $(terraformVersion)
    - task: TerraformTaskV2@2
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: 'aks_spn'
        backendAzureRmResourceGroupName: 'test-aks'
        backendAzureRmStorageAccountName: 'tfaks9'
        backendAzureRmContainerName: 'akstfstate'
        backendAzureRmKey: $(tfstatePath)
    - task: TerraformTaskV2@2
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        
- stage: Terraform_Deploy
  jobs:
  - job: Deploy
    displayName: TF Deployment
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: '1.0.7'
      
    - task: TerraformTaskV2@2
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: 'aks_spn'
        backendAzureRmResourceGroupName: 'test-aks'
        backendAzureRmStorageAccountName: 'tfaks9'
        backendAzureRmContainerName: 'akstfstate'
        backendAzureRmKey: $(tfstatePath)

    - task: TerraformTaskV2@2
      displayName: Terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '-out $(System.DefaultWorkingDirectory)/terraform/out.plan'
        environmentServiceNameAzureRM: 'aks_spn'

    - task: TerraformTaskV2@2
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '$(System.DefaultWorkingDirectory)/terraform/out.plan'
        environmentServiceNameAzureRM: 'aks_spn'

# - stage: Terraform_Destroy
#   displayName: Terraform Destroy
#   jobs:
#   - job: Destroy
#     displayName: Destroy
#     steps:
#     - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
#       displayName: Terraform installation
#       inputs:
#         terraformVersion: '1.0.7'

#     - task: TerraformTaskV2@2
#       displayName: Terraform init
#       inputs:
#         provider: 'azurerm'
#         command: 'init'
#         workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
#         backendServiceArm: 'aks_spn'
#         backendAzureRmResourceGroupName: 'test-aks'
#         backendAzureRmStorageAccountName: 'tfaks9'
#         backendAzureRmContainerName: 'akstfstate'
#         backendAzureRmKey: $(tfstatePath)

#     - task: TerraformTaskV1@0
#       displayName: 'Terraform Destroy'
#       inputs:
#         provider: 'azurerm'
#         command: 'destroy'
#         environmentServiceNameAzureRM: 'aks_spn'
#         workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'