# Steps
# Helm chart packaging & deployment

# Build Name
name: $(TeamProject)_$(SourceBranch)_$(BuildId) 

trigger:
- none

resources:
- repo: self

parameters:
  - name: environment
    type: string
    default: dev
    values:
    - dev
    - test
    - acc
    - prod
    
variables:
- template: ../cicd/variables/dev-variables.yml
- group: VariableGroup.GlobalVars

stages:
- stage: Helm_Chart_Packaging
  displayName: Helm Chart Packaging
  jobs:
  - job: Helm_Chart_Package
    displayName: Helm Chart Package
    pool:
      vmImage: ubuntu-latest  
    steps:
      - template: ../cicd/templates/helm-ci-template.yml
        parameters:
          dockerRegistry_sc: '$(dockerRegistry_sc)'
          projectName: '$(backendProjectName)'
          chartName: '$(chartName)'
          appVersion: '$(appVersion)'
          chartVersion: '$(chartVersion)'

- stage: Helm_Chart_Deploy
  displayName: Helm Chart Deployment
  jobs:
  - job: Helm_Chart_Deployment
    displayName: Helm Chart Deploy
    pool:
      vmImage: ubuntu-latest  
    steps:      
      - template: ../cicd/templates/helm-cd-template.yml
        parameters:
          dockerRegistry_sc: '$(dockerRegistry_sc)'
          projectName: '$(backendProjectName)'
          chartName: '$(chartName)'
          appVersion: '$(appVersion)'
          chartVersion: '$(chartVersion)'
          releaseName: '$(releaseName)'
