# Steps
# Junit Unit Tests
# Code Coverage Jacoco, Cabetura 
# Code compilation & static scan: sonarcube,PMD, FindBugs
# Docker image build & push

# Build Name
name: $(TeamProject)_$(SourceBranch)_$(BuildId) 

trigger:
- none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    type: string
    default: dev
    values:
    - dev
    - test
    - acc
    - prod
    
variables:
- template: ../cicd/variables/dev-variables.yml
- group: VariableGroup.GlobalVars

stages:
- stage: Java_Maven_Building
  displayName: Java Maven Building
  jobs:
  - job: Java_Maven_Build
    displayName: Java Maven Build  
    steps:
      - template: ../cicd/templates/maven-build-template.yml
        parameters:
          projectName: '$(backendprojectName)'

- stage: Docker_CI
  displayName: Docker CI
  jobs:
  - template: ../cicd/templates/docker-template.yml
    parameters:
      dockerRegistry_sc: '$(dockerRegistry_sc)'
      projectName: '$(backendprojectName)'
      chartName: '$(chartName)'
      appVersion: '$(appVersion)'
      chartVersion: '$(chartVersion)'
      acrName: '$(acrName)'