# Steps
# Junit Unit Tests
# Code Coverage Jacoco, Cabetura 
# Code compilation & static scan: sonarcube,PMD, FindBugs
# Docker image build & push
# Helm chart packaging & deployment


# Build Name
name: $(TeamProject)_$(SourceBranch)_$(BuildId) 

trigger:
- none

resources:
- repo: self

parameters:
  - name: acrName
    type: string
    default: testaks9acr9.azurecr.io
  - name: dockerRegistry_sc
    type: string
    default: testaks9acr9_sc
  - name: projectName
    type: string
    default: springboot-backend
  - name: chartName
    type: string
    default: backend-chart
  - name: appVersion
    type: string
    default: 1.16.0
  - name: chartVersion
    type: string
    default: 1.16.0
  - name: releaseName
    type: string
    default: sb
    
variables:
- template: ../pipelines/variables/cicd-variables.yml

stages:
- stage: Java_Maven_Building
  displayName: Java Maven Building
  jobs:
  - job: Java_Maven_Build
    displayName: Java Maven Build
    pool:
      vmImage: ubuntu-latest  
    steps:
      - template: ../pipelines/templates/maven-build-template.yml
        parameters:
          projectName: '${{ parameters.projectName }}'

- stage: Docker_Building_Pushing
  displayName: Docker Building Pushing
  jobs:
  - job: Docker_Build_Push
    displayName: Docker Build Push
    pool:
      vmImage: ubuntu-latest  
    steps:
      - template: ../pipelines/templates/docker-template.yml
        parameters:
          dockerRegistry_sc: '${{ parameters.dockerRegistry_sc }}'
          projectName: '${{ parameters.projectName }}'
          chartName: '${{ parameters.chartName }}'
          appVersion: '${{ parameters.appVersion }}'
          chartVersion: '${{ parameters.chartVersion }}'
          acrName: '${{ parameters.acrName }}'

- stage: Helm_Chart_Packaging
  displayName: Helm Chart Packaging
  jobs:
  - job: Helm_Chart_Package
    displayName: Helm Chart Package
    pool:
      vmImage: ubuntu-latest  
    steps:
      - template: ../pipelines/templates/helm-ci-template.yml
        parameters:
          dockerRegistry_sc: '${{ parameters.dockerRegistry_sc }}'
          projectName: '${{ parameters.projectName }}'
          chartName: '${{ parameters.chartName }}'
          appVersion: '${{ parameters.appVersion }}'
          chartVersion: '${{ parameters.chartVersion }}'

- stage: Helm_Chart_Deploy
  displayName: Helm Chart Deployment
  jobs:
  - job: Helm_Chart_Deployment
    displayName: Helm Chart Deloy
    pool:
      vmImage: ubuntu-latest  
    steps:      
      - template: ../pipelines/templates/helm-cd-template.yml
        parameters:
          dockerRegistry_sc: '${{ parameters.dockerRegistry_sc }}'
          projectName: '${{ parameters.projectName }}'
          chartName: '${{ parameters.chartName }}'
          appVersion: '${{ parameters.appVersion }}'
          chartVersion: '${{ parameters.chartVersion }}'
          releaseName: '${{ parameters.releaseName }}'
