
trigger:
- none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '996a8bb4-7de3-4358-959a-93145356536d'
  acrPassword: 'ajrVdZkJKO4/cL2h5Drq7YOPx15w7bzf'
  containerRegistry: 'testaks9acr9.azurecr.io'
  acrname: 'testaks9acr9'
  aks: 'testaks9'
  aksrg: 'test-aks'
  projectName: 'springboot-backend'
  chartName: backend-chart
  appVersion: 1.16.0
  chartVersion: 1.16.0
  
steps:
    - task: Docker@2
      displayName: 'Build & Push Docker Image to ACR'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(projectName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(appVersion)'
        
    - task: HelmInstaller@0
      displayName: 'Install Helm'
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
        
    - task: HelmDeploy@0
      displayName: Save Helm Package to ACR
      inputs:
        azureSubscriptionForACR: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        azureResourceGroupForACR: $(aksrg)
        azureContainerRegistry: $(containerRegistry)
        command: 'save'
        chartNameForACR: $(chartName)
        chartPathForACR: '$(projectName)/$(chartName)'
      env:
        HELM_EXPERIMENTAL_OCI: 1
        
    - task: AzureCLI@2
      displayName: Download Helm Chart from ACR
      inputs:
        azureSubscription: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrname)
          az acr helm repo add --name $(acrname)
          echo $(acrPassword) | helm registry login $(containerRegistry) --username $(acrname) --password-stdin
          helm repo update
          helm chart pull $(containerRegistry)/helm/$(chartName):$(chartVersion)
          helm chart export $(containerRegistry)/helm/$(chartName):$(chartVersion) --destination .
      env:
        HELM_EXPERIMENTAL_OCI: 1

    - task: HelmDeploy@0
      displayName: Helm Package Deployment in AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        azureResourceGroup: $(aksrg)
        kubernetesCluster: $(aks)
        useClusterAdmin: true
        namespace: 'default'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: '$(projectName)/$(chartName)'
        releaseName: 'dev'
        arguments: '--create-namespace'
      
    
    
