apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-backend
  name: springboot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-backend
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      containers:
      - image: bahrinipun/springboot-backend:v1.2
        name: springboot-backend
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: springbootconfig
              key: MYSQLCONNECTION
