apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-backend
  name: springboot-backend
spec:
  externalName: springboot-backend.com
  ports:
  - name: backend-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-backend
  type: ExternalName
