
trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      continueOnError: true
      displayName: "Linting Dockerfile"
      inputs:
        targetType: 'inline'
        script: |
          docker run --rm -i hadolint/hadolint < '$(Build.SourcesDirectory)/springboot-backend/Dockerfile'
          
          # check if the Hadolint command found issues or not
          if [ $? != 0 ];
          then
            echo "##vso[task.logissue type=error]Lint scanning found errors in the Dockerfile that need to be resolved!"
            echo "##vso[task.complete result=Failed]Docker Lint reporting errors"
          else
            echo "##vso[task.complete result=Succeeded]Docker Lint succeeded"
          fi

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub_sc'
        repository: 'bahrinipun/sb'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/springboot-backend/Dockerfile'
        buildContext: '$(Build.ArtifactStagingDirectory)'
        tags: '1.60'
        arguments: '--no-cache'

    - task: Bash@3
      displayName: Download & Install Trivy For Image Scan
      inputs:
        targetType: 'inline'
        script: |
          docker images
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.19.2_Linux-64bit.deb
          trivy -v


    - task: Bash@3
      displayName: Trivy Scan
      inputs:
        targetType: 'inline'
        script: |
          set -euo pipefail
          trivy image --exit-code 0 --severity LOW,MEDIUM bahrinipun/sb:1.60
          trivy image --severity LOW,MEDIUM --format template --template '$(Build.SourcesDirectory)/templates/junit.tpl' -o junit-report-low-med.xml bahrinipun/sb:1.60

    - task: Bash@3
      displayName: Trivy Scan
      inputs:
        targetType: 'inline'
        script: |
          set -euo pipefail

          trivy image \
            --ignore-unfixed \
            --format template \
            --template '$(Build.SourcesDirectory)/templates/junit.tpl' \
            -o junit-report.xml \
            bahrinipun/sb:1.60

    - task: PublishTestResults@2
      displayName: 'Publish Trivy Scan Results'
      inputs:
        testResultsFormat: 'JUnit' 
        testResultsFiles: 'junit-report.xml' 
        failTaskOnFailedTests: false
        testRunTitle: 'Trivy Image Scan'
          
    - task: Docker@2
      displayName: Push Image
      inputs:
        containerRegistry: 'dockerhub_sc'
        repository: 'bahrinipun/sb'
        command: 'push'
        tags: '1.60'

    - task: ContainerStructureTest@0
      inputs:
        dockerRegistryServiceConnection: 'dockerhub_sc'
        repository: 'bahrinipun/sb'
        tag: '1.60'
        configFile: '$(Build.SourcesDirectory)/cicd/structure-test.yaml'
        testRunTitle: 'Structure Test'
        failTaskOnFailedTests: false