server:
  port: 8080
 
spring: 
 profiles:
    active: ${spring.profiles.active}

---
spring:
  profiles: local
  datasource:
    username: mysql
    url: jdbc:mysql://localhost:3306/sample
    password: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
management:
  security:
    enabled: 'false'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
exception:
  message: Employee Not Found in Local Database
  
---
spring:
  profiles: dev
  datasource:
    username: ${spring.datasource.username}
    url: jdbc:sqlserver://${db.server.name}.database.windows.net:1433;database=${db.name};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    #url: jdbc:sqlserver://${db.server.name}.database.windows.net:1433;database=${db.name};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;Authentication=ActiveDirectoryMSI
    password: ${spring.datasource.password}
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
exception:
  message: Employee Not Found in Dev Database

