server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore/fullstack.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: fullstack  
spring: 
 profiles:
    active: '@spring.profiles.active@'

---
spring:
  profiles: local
  datasource:
    username: mysql
    url: jdbc:mysql://localhost:3306/sample
    password: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
management:
  security:
    enabled: 'false'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
exception:
  message: Employee Not Found in Local Database
  skillMessage: Skill Not Found in Local Database
  
---
spring:
  profiles: dev
  datasource:
    #username: ${DB_USER}
    #password: ${DB_PASS}
    #url: jdbc:sqlserver://testsqldbserver9.database.windows.net:1433;database=testsqldb9;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    url: jdbc:sqlserver://testsqldbserver9.database.windows.net:1433;database=testsqldb9;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;Authentication=ActiveDirectoryMSI
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
exception:
  message: Employee Not Found in Dev Database
  skillMessage: Skill Not Found in Local Database

