spring:
  datasource:
    username: ''
    url: ''
    password: ''
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
management:
  security:
    enabled: 'false'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
