trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- template: iac-variables/cicd-variables.yml

stages:
- stage: Terraform_Validate
  jobs:
  - job: Validate
    displayName: Validation
    steps:
    - task: AzureCLI@2
      displayName: 'Get Latest Kubernetes Version'
      inputs:
        azureSubscription: $(service_connection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          version=$(az aks get-versions --location $(location) --query orchestrators[-1].orchestratorVersion --output tsv)
          echo "##vso[task.setvariable variable=kubernetesVersion;]$version"
          echo "kubernetesVersion: $(kubernetesVersion)"
        #addSpnToEnvironment: true
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: $(terraformVersion)
    - task: TerraformTaskV2@2
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: $(service_connection)
        backendAzureRmResourceGroupName: $(aks_rg)
        backendAzureRmStorageAccountName: $(sac)
        backendAzureRmContainerName: $(sac_container)
        backendAzureRmKey: $(tfstatePath)
    - task: TerraformTaskV2@2
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        
- stage: Terraform_Deploy
  jobs:
  - job: Deploy
    displayName: TF Deployment
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Terraform installation
      inputs:
        terraformVersion: '1.0.7'
      
    - task: TerraformTaskV2@2
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: $(service_connection)
        backendAzureRmResourceGroupName: $(aks_rg)
        backendAzureRmStorageAccountName: $(sac)
        backendAzureRmContainerName: $(sac_container)
        backendAzureRmKey: $(tfstatePath)

    - task: TerraformTaskV2@2
      displayName: Terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '-out $(System.DefaultWorkingDirectory)/terraform/out.plan'
        environmentServiceNameAzureRM: $(service_connection)

    - task: TerraformTaskV2@2
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '$(System.DefaultWorkingDirectory)/terraform/out.plan'
        environmentServiceNameAzureRM: $(service_connection)