trigger: none

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
- template: bicep-variables.yml
  
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Bicep_Build
  displayName: Bicep Build
  condition: and(succeeded(),ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Lint_Bicep
    displayName: Lint Bicep
    steps:
      - task: AzureCLI@2
        name: LintBicepCode
        displayName: Run Bicep linter
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptPath: "$(Build.SourcesDirectory)/demo-fullstack/iac/scripts/lint.sh"
        env:
          BICEP_FILENAME: $(templateFile)
          SOURCE_DIR: $(Build.SourcesDirectory)
            
  - job: Validate_Bicep
    displayName: Validate_Bicep
    steps:       
       - task: AzureCLI@2
         name: RunPreflightValidation
         displayName: Run preflight validation
         inputs:
           azureSubscription: $(azureServiceConnection)
           scriptType: 'bash'
           scriptPath: "$(Build.SourcesDirectory)/demo-fullstack/iac/scripts/validation.sh"
         env:
           RESOURCE_GROUP_NAME: $(resourceGroupName)
           BICEP_FILENAME: $(templateFile)
           PARAMETER_FILENAME: $(parameterFileName)
           ENV: "${{ parameters.environment }}"
           SOURCE_DIR: $(Build.SourcesDirectory)
           REPO_NAME: $(Build.Repository.Name)
           TEST_DIR: "${{ parameters.testDir }}"
            
  - job: Preview_Azure_Changes
    displayName: Preview Azure changes
    steps:
      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptPath: "$(Build.SourcesDirectory)/demo-fullstack/iac/scripts/whatif.sh"
        env:
          RESOURCE_GROUP_NAME: $(resourceGroupName)
          BICEP_FILENAME: $(templateFile)
          PARAMETER_FILENAME: $(parameterFileName)
          ENV: "${{ parameters.environment }}"
          SOURCE_DIR: $(Build.SourcesDirectory)
          REPO_NAME: $(Build.Repository.Name)
          TEST_DIR: "${{ parameters.testDir }}"
              
- stage: Bicep_Deploy
  displayName: Bicep Deploy
  dependsOn: Bicep_Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
      - task: AzureCLI@2
        name: DeployBicepFile
        displayName: Deploy Bicep file
      inputs:
        azureSubscription: ${{ parameters.resourceGroupName }}
        scriptType: 'bash'
        scriptPath: "$(Build.SourcesDirectory)/demo-fullstack/iac/scripts/deployment.sh"
      env:
        RESOURCE_GROUP_NAME: "${{ parameters.resourceGroupName }}"
        BICEP_FILENAME: "${{ parameters.bicepFileName }}"
        PARAMETER_FILENAME: "${{ parameters.parameterFileName }}"
        ENV: "${{ parameters.environment }}"
        DEPLOYMENT_NAME: "${{ parameters.deploymentName }}"
        BICEP_ACTION: "create"
        SOURCE_DIR: $(Build.SourcesDirectory)
        REPO_NAME: $(Build.Repository.Name)
        TEST_DIR: "${{ parameters.integrationTestDir }}"
