# AKS Prerequsites pipeline
# DevOps SPN and permissions & role assignment
# Server SPN & role assignment
# Storage Account for terraform state
# Key vault for storing secrets such as ssh key, spn secrets

trigger:
- none

# Build Name
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'sub_sc'
  resourceGroupName: 'exampleRG'
  location: 'westeurope'
  templateFile: 'iac/prerequisites/createSacDeploy.bicep'
pool:
  vmImage: $(vmImageName)

stages:
- stage: Bicep_Lint
  displayName: Bicep Lint
  jobs:
  - job: Lint
    displayName: Lint
    steps:
      - task: AzureCLI@2
        name: Lint_Bicep_Code
        displayName: Lint Bicep Code
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |        
            az bicep build --file $(templateFile)
            
- stage: Validate
  displayName: Validate Bicep
  variables:
    - template: variables.yml  
  jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep code
    steps:       
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group validate \
              --resource-group $(resourceGroupName) \
              --template-file $(templateFile)
            
- stage: Preview Bicep
  variables:
    - template: variables.yml
  jobs: 
  - job: PreviewAzureChanges
    displayName: Preview Azure changes
    steps:
      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group what-if \
              --resource-group $(resourceGroupName) \
              --template-file $(templateFile)
              
- stage: Bicep_Deploy
  displayName: Bicep Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureCLI@2
      displayName: Bicep SAC Deployment
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)
