# AKS Prerequsites pipeline
# DevOps SPN and permissions & role assignment
# Server SPN & role assignment
# Storage Account for terraform state
# Key vault for storing secrets such as ssh key, spn secrets

trigger:
- none

# Build Name
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'sub_sc'
  resourceGroupName: 'exampleRG'
  location: 'westeurope'
  templateFile: './prerequisites/createSacDeploy.bicep'
pool:
  vmImage: $(vmImageName)

stages:
- stage: Bicep_Lint
  displayName: Bicep Lint
  jobs:
  - job: Lint
    displayName: Lint
    steps:
      - task: AzureCLI@2
        name: Lint_Bicep_Code
        displayName: Lint Bicep Code
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |        
            ls -lrt
            ls -lrt iac/
            ls -lrt iac/prerequisites/
            az bicep build --file .iac/prerequisites/createSacDeploy.bicep
            
- stage: Bicep_Deploy
  displayName: Bicep Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureCLI@2
      displayName: Bicep SAC Deployment
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment sub create --template-file $(templateFile) -l 'westeurope'
