# AKS Prerequsites pipeline
# DevOps SPN and permissions & role assignment
# Server SPN & role assignment
# Storage Account for terraform state
# Key vault for storing secrets such as ssh key, spn secrets

trigger:
- none

# Build Name
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
- template: bicep-variables.yml
  
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Bicep_Build
  displayName: Bicep Build
  jobs:
  - job: Lint_Bicep
    displayName: Lint Bicep
    steps:
      - task: AzureCLI@2
        name: Lint_Bicep_Code
        displayName: Lint Bicep Code
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |        
            az bicep build --file $(templateFile)
            
  - job: Validate_Bicep
    displayName: Validate_Bicep
    steps:       
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group validate \
              --resource-group $(resourceGroupName) \
              --template-file $(templateFile) --parameters rgName=$(resourceGroupName) sqlServerName=$(sqlServerName) sqlServerDBName=$(sqlServerDBName) keyVaultName=$(keyVaultName)
            
  - job: Preview_Azure_Changes
    displayName: Preview Azure changes
    steps:
      - task: AzureCLI@2
        name: Preview
        displayName: Preview Run
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group what-if \
              --resource-group $(resourceGroupName) \
              --template-file $(templateFile) --parameters rgName=$(resourceGroupName) sqlServerName=$(sqlServerName) sqlServerDBName=$(sqlServerDBName) keyVaultName=$(keyVaultName)
              
- stage: Bicep_Deploy
  displayName: Bicep Deploy
  dependsOn: Bicep_Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureCLI@2
      displayName: Bicep Deployment
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters rgName=$(resourceGroupName) sqlServerName=$(sqlServerName) sqlServerDBName=$(sqlServerDBName) keyVaultName=$(keyVaultName)
