
trigger:
- master

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd6e7b3b6-e634-4138-8e27-3ff952063801'
  imageRepository: 'react-frontend'
  containerRegistry: 'testaksacr9.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'testaksacr91577d987-auth'

steps:
    # - task: Docker@2
    #   displayName: Build and push an image to container registry
    #   inputs:
    #     containerRegistry: '$(dockerRegistryServiceConnection)'
    #     repository: '$(imageRepository)'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'
    #     addPipelineData: false
    #     addBaseImageData: false
        
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
        
    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: 'react-frontend/frontend-chart'
        
    - bash: |
        helm version
        export HELM_EXPERIMENTAL_OCI=1
        helm chart push testaksacr9.azurecr.io/helm/react-frontend:$(tag)
      failOnStderr: true
      name: helmPush
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
      displayName: 'Helm push'
        
    
