
trigger:
- none

resources:
- repo: self

parameters:
  - name: dockerRegistry_sc
    type: string
    default: testaks9acr9_sc
  - name: projectName
    type: string
    default: react-frontend
  - name: chartName
    type: string
    default: frontend-chart
  - name: appVersion
    type: string
    default: 1.16.0
  - name: chartVersion
    type: string
    default: 1.16.0

variables:
  acrPassword: 'hS=gdMACcSIsx0i5N88iwQrwZmZPRdmu'
  containerRegistry: 'testaks9acr9.azurecr.io'
  acrname: 'testaks9acr9'
  aks: 'testaks9'
  aksrg: 'test-aks'

stages:
- stage: Helm_Packaging
  displayName: Helm Packaging
  jobs:
  - job: Helm_Package
    displayName: Helm Package
    pool:
      vmImage: ubuntu-latest  
    steps:
      - template: ../pipelines/templates/helm-ci-template.yml
        parameters:
          dockerRegistry_sc: '${{ parameters.dockerRegistry_sc }}'
          projectName: '${{ parameters.projectName }}'
          chartName: '${{ parameters.chartName }}'
          appVersion: '${{ parameters.appVersion }}'
          chartVersion: '${{ parameters.chartVersion }}'

- stage: Helm_Deploy
  displayName: Helm Deployment
  jobs:
  - job: Helm_Deployment
    displayName: Helm Deloy
    pool:
      vmImage: ubuntu-latest  
    steps:      
      - template: ../pipelines/templates/helm-cd-template.yml
        parameters:
          dockerRegistry_sc: '${{ parameters.dockerRegistry_sc }}'
          projectName: '${{ parameters.projectName }}'
          chartName: '${{ parameters.chartName }}'
          appVersion: '${{ parameters.appVersion }}'
          chartVersion: '${{ parameters.chartVersion }}'