
trigger:
- master

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd6e7b3b6-e634-4138-8e27-3ff952063801'
  imageRepository: 'react-frontend'
  containerRegistry: 'testaksacr9.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'testaksacr91577d987-auth'
  acrPassword: 'VVKYOBOjvEgDcZsTbQxnTMtopFqrbN=W'
  username: 'testaksacr9'
  aks: 'testaks'
  rg: 'test-aks'
  projectName: 'react-frontend'
  replicas: '1'
  imgVersion: '400'
  # attach AKS ACR - az aks update -n testaks -g test-aks --attach-acr testaksacr9

steps:
    - task: Docker@2
      displayName: 'Build & Push Docker Image to ACR'
      inputs:
        containerRegistry: 'testaksacr9'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        
    - task: HelmInstaller@0
      displayName: 'Install Helm'
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
        
    - task: HelmDeploy@0
      displayName: 'Save Helm Package to ACR'
      inputs:
        azureSubscriptionForACR: 'Nipun Bahri Subscription(1)(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        azureResourceGroupForACR: 'test-aks'
        azureContainerRegistry: 'testaksacr9.azurecr.io'
        command: 'save'
        chartNameForACR: '$(projectName)'
        chartPathForACR: '$(containerRegistry)'
        
    # - bash: |
    #     helm version
    #     export HELM_EXPERIMENTAL_OCI=1
    #     cd react-frontend/frontend-chart
    #     helm chart save . $(projectName):0.1.0
    #     helm chart save . $(containerRegistry)/helm/$(projectName):0.1.0
    #     echo $(acrPassword) | helm registry login $(containerRegistry) --username $(username) --password-stdin
    #     helm chart push $(containerRegistry)/helm/$(projectName):0.1.0
    #   failOnStderr: true
    #   name: helmPush
    #   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    #   displayName: 'Helm push'
      
    # - bash: |
    #     helm repo add testaksacr9 https://testaksacr9.azurecr.io/helm/v1/repo --username testaksacr9 --password 6lps+e22wxBZWjdIcsg3YQhKvoo+dLpj
    #     helm repo update

    #     helm upgrade \
    #     --namespace default \
    #     --create-namespace \
    #     --install \
    #     --wait \
    #     --set image.repository=$(containerRegistry)/$(projectName) \
    #     --set image.tag=$imgVersion \
    #     --set replicaCount=$(replicas) \
    #     frontend-chart \
    #     ./frontend-chart
    #   failOnStderr: true
    #   name: helmCred
    #   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    #   displayName: 'Helm Cred'
      
    
    
