
trigger:
- none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e2d0e05b-235c-435c-b140-80d35117509c'
  acrPassword: 'eJPgnlcoCHecAbBV/PVxsRrYH47LkfyG'
  containerRegistry: 'testaks9acr9.azurecr.io'
  imageRepository: 'react-frontend'  
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  username: 'testaks9acr9'
  projectName: 'react-frontend'
  chartName: frontend-chart
  chartVersion: 0.1.0
  # Attach AKS ACR - az aks update -n testaks9 -g test-aks --attach-acr testaks9acr9

steps:
    - task: Docker@2
      displayName: 'Build & Push Docker Image to ACR'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        
    - task: HelmInstaller@0
      displayName: 'Install Helm'
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
        
    - task: HelmDeploy@0
      displayName: Save Helm Package to ACR
      inputs:
        azureSubscriptionForACR: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        azureResourceGroupForACR: 'test-aks'
        azureContainerRegistry: 'testaks9acr9.azurecr.io'
        command: 'save'
        chartNameForACR: 'frontend-chart'
        chartPathForACR: 'react-frontend/frontend-chart'
      env:
        HELM_EXPERIMENTAL_OCI: 1
        
    - task: AzureCLI@2
      displayName: Download Helm Chart from ACR
      inputs:
        azureSubscription: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr repository list -n testaks9acr9
          az acr helm repo add --name testaks9acr9
          echo $(acrPassword) | helm registry login $(containerRegistry) --username $(username) --password-stdin
          helm repo update
          helm chart pull $(containerRegistry)/helm/$(chartName):$(chartVersion)
          helm chart export $(containerRegistry)/helm/$(chartName):$(chartVersion) --destination .
      env:
        HELM_EXPERIMENTAL_OCI: 1

    - task: HelmDeploy@0
      displayName: Helm Package Deployment in AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Nipun Bahri Subscription(bf0f6779-86d2-467e-8226-10f92a8ad378)'
        azureResourceGroup: 'test-aks'
        kubernetesCluster: 'testaks9'
        useClusterAdmin: true
        namespace: 'default'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: '$(projectName)/$(chartName)'
        releaseName: 'dev'
        arguments: '--create-namespace'
      
    
    
