apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-frontend
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-frontend
    spec:
      containers:
      - image: react-frontend:v1.0
        name: react-frontend
        resources: {}
status: {}
