apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-frontend
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-frontend
    spec:
      containers:
      - image: bahrinipun/react-frontend:v1.2
        name: react-frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_EMPLOYEE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: reactconfig
              key: EMPLOYEE_API_BASE_URL_VALUE
        resources: {}
status: {}
