# Following are steps planned within this pipeline
#
# Create KeyVault

# Build Name
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Lint
  displayName: Lint Bicep
  jobs:
  - job: LintCode
    displayName: Lint code
    steps:
      - task: AzureCLI@2
        name: LintCode
        displayName: Lint code
        inputs:
          azureSubscription: cgt-d-rg
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |            
            az bicep build --file ../iac/main.bicep

- stage: Validate
  displayName: Validate Bicep
  variables:
    - template: variables.yml  
  jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep code
    steps:
      - task: FileTransform@1
        displayName: 'File transformation: pattern.template.parameters.json'
        inputs:
          folderPath: '.'
          targetFiles: 'pattern.template.parameters.json'
          fileType: json

      - task: AzureCLI@2
        name: Preflight_Validation
        displayName: Preflight Validation
        inputs:
          azureSubscription: cgt-d-rg
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group validate \
              --resource-group cgt-d-rg \
              --template-file ../iac/main.bicep --parameters @pattern.template.parameters.json

- stage: Preview_Changes
  displayName: Preview Infra Changes
  variables:
    - template: variables.yml
  jobs: 
  - job: Preview_Azure_Changes
    displayName: Preview Azure changes
    steps:
      - task: FileTransform@1
        displayName: 'File transformation: pattern.template.parameters.json'
        inputs:
          folderPath: '.'
          targetFiles: 'pattern.template.parameters.json'
          fileType: json

      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
          azureSubscription: cgt-d-rg
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group what-if \
              --resource-group cgt-d-rg \
              --template-file ../iac/main.bicep --parameters @pattern.template.parameters.json

- stage: Deploy
  displayName: Deploy Infra
  variables:
    - template: variables.yml
  jobs:
  - deployment: DeployMyInfra
    displayName: Deploy MyInfra
    environment: RK-Environment
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: FileTransform@1
              displayName: 'File transformation: pattern.template.parameters.json'
              inputs:
                folderPath: '.'
                targetFiles: 'pattern.template.parameters.json'
                fileType: json
            - task: AzureCLI@2
              name: DeployBicepFile
              displayName: Deploy Bicep file
              inputs:
                azureSubscription: cgt-d-rg
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create \
                    --name samplePatternDeployment \
                    --resource-group cgt-d-rg \
                    --template-file ../iac/main.bicep --parameters @pattern.template.parameters.json